#!/usr/bin/env python

import logging
import os
import sys
from time import sleep

# import external library
sys.path.append('/var/service')
from runit_helper import (
    MAXIMUM_CRASHES_DELAY,
    check_crash_quota,
    check_dependencies,
    get_logger,
    run,
)

service_name = 'sshd'

log = get_logger(service_name, logging.INFO)

check_dependencies(service_name, log)

if check_crash_quota(service_name):
    sleep(MAXIMUM_CRASHES_DELAY)
    exit(0)

log.info('starting..')

# configurations
CONFIGFILE = '/etc/ssh/sshd_config'
EXECUTABLE = '/usr/sbin/sshd'
USER = 'root'
GROUP = 'root'

# init
if not os.path.exists('/var/empty'):
    os.makedirs('/var/empty')
if os.system('%s -f "%s" -t' % (EXECUTABLE, CONFIGFILE)):
    log.error('invalid configuration %s' % CONFIGFILE)
    exit(1)

run(EXECUTABLE, [
    '-f', CONFIGFILE,
    '-D',
], user=USER, group=GROUP)
