#!/usr/bin/env python

import logging
import os
import sys
from time import sleep

# import external library
sys.path.append('/var/service')
from runit_helper import (
    MAXIMUM_CRASHES_DELAY,
    check_crash_quota,
    check_dependencies,
    get_logger,
    run,
)

service_name = 'spamd'

log = get_logger(service_name, logging.INFO)

check_dependencies(service_name, log)

if check_crash_quota(service_name):
    sleep(MAXIMUM_CRASHES_DELAY)
    exit(0)

log.info('starting..')

# configurations
EXECUTABLE = '/usr/sbin/spamd'
HOME_DIR = '/var/lib/spamassassin'
USER = 'vmail'
GROUP = 'vmail'

run(EXECUTABLE, [
    '--create-prefs',
    '--nouser-config',
    '--max-children=3',
    '--helper-home-dir={home}'.format(home=HOME_DIR),
    '--virtual-config-dir={home}/users/%d/%l'.format(home=HOME_DIR),
    '--username={user}'.format(user=USER),
    '--groupname={group}'.format(group=GROUP),
])
