#!/usr/bin/env python

import sys

# import external library
sys.path.append('/var/service')
from runit_helper import (
    update_crash_log,
)

service_name = 'syslog-ng'

exit_code = sys.argv[1]
status = sys.argv[2]

if exit_code == 111 and status == 0:
    print('runsv cannot start ./run')
elif exit_code == 0:
    print('stopped with signal %s' % status)
else:
    print('crashed with code %s' % exit_code)
    update_crash_log(service_name)
