#!/usr/bin/env python

import os
import sys

# import external library
sys.path.append('/var/service')
from runit_helper import run
# The functions above are examples and default configuration,
# you should write your own for custom implementation.

# This must be the same as the directory name,
# it will be used to poll the status of the service using sv.
service_name = '_skeleton_'


# Configurations, these are just normal python variables
LOG_PATH = '/var/log/%s' % service_name


# Run svlogd, runit logger program.
if not os.path.exists(LOG_PATH):  os.makedirs(LOG_PATH)
run('/usr/bin/svlogd', ['-tt', LOG_PATH], redirect=False)
