#!/usr/bin/env python

from os import listdir, path, system
from signal import pause, signal, SIG_DFL, SIGHUP, SIGINT, SIGTERM
from subprocess import Popen, STDOUT

# services
services = []
users = (d for d in listdir('/home') if path.lexists('/home/%s/service' % d)) 

for user in users:
    handle = Popen(' '.join([
            '/usr/bin/chpst',
            '-u {uid}:{uid}'.format(uid=user),
            '/usr/bin/runsvdir /home/%s/service' % user,
        ]),
	shell=True,
        stderr=STDOUT,
    )
    services.append(handle)

def on_shutdown(sign, frame):
    for service in services:
        service.send_signal(SIGHUP)
    for service in services:
        service.wait()
    exit(0)

signal(SIGINT, on_shutdown)
signal(SIGTERM, on_shutdown)

while len([s for s in services if s.returncode is None]):
    pause()
