#!/usr/bin/env python

import logging
import sys

# import external library
sys.path.append('/var/service')
from runit_helper import (
    get_logger,
    stop_dependant_services,
    update_crash_log,
)

service_name = 'ntpd'

log = get_logger(service_name, logging.INFO)
exit_code = int(sys.argv[1])
status = int(sys.argv[2])

if exit_code == 111 and status == 0:
    log.error('runsv cannot start ./run')
elif exit_code == 0:
    log.info('stopped with signal %s' % status)
else:
    log.warn('crashed with code %s' % exit_code)
    update_crash_log(service_name)

stop_dependant_services(service_name, log)
